name = "Minecraft 1.20 Server Pack"
author = "oskardotglobal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82e5b83d786a3f79b24ebeed9ac10706e7cbadbbb2f288569bcd55d0b6e46ff5"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
